---
- name: install mysql-server
  apt: name=mysql-server state=present

- name: install mysql-client
  apt: name=mysql-client state=present

- name: install mysql-python
  apt: name=python-mysqldb state=present

- name: Añadiendo base de datos
  mysql_db: name=servermail
            state=present

- name: Añadir usuario a la base de datos
  mysql_user: name=usermail
              host=127.0.0.1
              password=mailpassword
              priv=servermail.*:ALL,GRANT
              login_user=root
              login_password=

  notify:
        - reiniciando mysql
