---
- name: install php
  apt: name=php5 state=present
- name: install php5 packages
  apt: name={{ item }}
       state=latest
  with_items:
        - php5-mysql
        - libapache2-mod-php5
        - php5-mcrypt
        - php5-json
        - php5-imap
