---
- name: install postfix
  apt: name=postfix state=present

- name: install postfix-mysql
  apt: name=postfix-mysql state=present

- name: create necessary directories
  file: path=/etc/postfix/sql state=directory

- name: moving configuration file main.cf
  template:
     src=postfix/main.cf.j2
     dest=/etc/postfix/main.cf

- name: moving certificate
  copy: 
     src=certs/dovecot.pem
     dest=/etc/ssl/certs/dovecot.pem

- name: moving key
  copy: 
     src=private/dovecot.pem
     dest=/etc/ssl/private/dovecot.pem

- name: moving configuration file master.cf
  template:
     src=postfix/master.cf.j2
     dest=/etc/postfix/master.cf

- name: moving configuration file mysql_virtual_alias_domain_maps.cf
  template:
     src=postfix/sql/mysql_virtual_alias_domain_maps.cf.j2
     dest=/etc/postfix/sql/mysql_virtual_alias_domain_maps.cf

- name: moving configuration file mysql_virtual_alias_domain_mailbox_maps.cf
  template:
     src=postfix/sql/mysql_virtual_alias_domain_mailbox_maps.cf.j2
     dest=/etc/postfix/sql/mysql_virtual_alias_domain_mailbox_maps.cf

- name: moving configuration file mysql_virtual_alias_domain_catchall_maps.cf
  template:
     src=postfix/sql/mysql_virtual_alias_domain_catchall_maps.cf.j2
     dest=/etc/postfix/sql/mysql_virtual_alias_domain_catchall_maps.cf

- name: moving configuration file mysql_virtual_alias_maps.cf
  template:
     src=postfix/sql/mysql_virtual_alias_maps.cf.j2
     dest=/etc/postfix/sql/mysql_virtual_alias_maps.cf

- name: moving configuration file mysql_virtual_domains_maps.cf
  template:
     src=postfix/sql/mysql_virtual_domains_maps.cf.j2
     dest=/etc/postfix/sql/mysql_virtual_domains_maps.cf

- name: moving configuration file mysql_virtual_mailbox_limit_maps.cf
  template:
     src=postfix/sql/mysql_virtual_mailbox_limit_maps.cf.j2
     dest=/etc/postfix/sql/mysql_virtual_mailbox_limit_maps.cf

- name: moving configuration file mysql_virtual_mailbox_maps.cf
  template:
     src=postfix/sql/mysql_virtual_mailbox_maps.cf.j2
     dest=/etc/postfix/sql/mysql_virtual_mailbox_maps.cf

  notify:
      - reiniciando postfix
